name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # downloads the repository code to the runner
      # this process is automated by github actions
      # we only need to specify the action to use
      - name: Checkout code
        uses: actions/checkout@v2

        # sets up python 3.12 on the runner
        # similar to the previous step, we only need to specify the action to use
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

        # installs the dependencies required to run the tests
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt

        # runs the tests
      - name: Run tests
        run: |
          pytest . -vv
